void getVec2Instance(HSQUIRRELVM v, int idx, b2Vec2* vec2);
void getVec2InstanceFromMember(HSQUIRRELVM v, int idx, const char* member, b2Vec2* vec2);
void pushVec2(HSQUIRRELVM v, b2Vec2 vec2);
void getBodyDefInstance(HSQUIRRELVM v, int idx, b2BodyDef* def);
void getFixtureDefInstance(HSQUIRRELVM v, int idx, b2FixtureDef* def);
void getDistanceJointDef(HSQUIRRELVM v, int idx, b2DistanceJointDef* def);
void getFrictionJointDef(HSQUIRRELVM v, int idx, b2FrictionJointDef* def);
void getGearJointDef(HSQUIRRELVM v, int idx, b2GearJointDef* def);
void getLineJointDef(HSQUIRRELVM v, int idx, b2LineJointDef* def);
void getPrismaticJointDef(HSQUIRRELVM v, int idx, b2PrismaticJointDef* def);
void getPulleyJointDef(HSQUIRRELVM v, int idx, b2PulleyJointDef* def);
void getRevoluteJointDef(HSQUIRRELVM v, int idx, b2RevoluteJointDef* def);
void getWeldJointDef(HSQUIRRELVM v, int idx, b2WeldJointDef* def);
